#include "../../wto.mac"
#include "../../pre.mac"
#include "../../post.mac"
#include "../../prestack.mac"
#include "../../cpmcommon.mac"
#include "../../fcb.mac"
#include "../../fileopen.mac"
#include "../../fileseek.mac"
#include "../../fread.mac"
#include "../../fileclose.mac"
#include "../../fmerr.mac"
#include "../../packfd.mac"
#include "../../memset.mac"
#include "../../strcpy.mac"
#include "../../setdma.mac"
#include "../../printl.mac"
#include "../../puts.mac"
#include "../../putc.mac"
#include "../../display.mac"
#include "../../startp.mac"
#include "../../radix.mac"
#include "../../mod.mac"
#include "../../comp.mac"
#include "../../divide.mac"
#include "../../multip.mac"
#include "../../binascii.mac"
#include "../../snap.mac"

	common	
NEWLN	equ	0ah
SPACE	equ	20h
	org	100h
	pre
	startp	front,list,count
	; create a dummy file name and use packfd to fill in the
	; fcb.  then read the intended name from the start up
	; parameters, given at the command line.
	packfd	rdfcb,'TESTFILE.TXT'
	; use packfn to replace the dummy file name.
	; hl still points to rdfcb
;	memset	filenm,0,16
;	strcpy	filenm,argb,16,0
;	memset	rdfcb,0,fcbsz
	lxi	h,rdfcb
	xchg
	lhld	list
	;lxi	h,;name
; put in the file name and drive the user specified
	call	packfn	
	lxi	h,rdfcb
; open the file
	open	hl
; read a record
loop	fread	rdfcb	
	ora	a
	jnz	finish	; eof condition
; prime the record counter
	mvi	a,128
	sta	rcnt
; while(c=getchar(hl++) != NULL){
;  putc(c); rcnt--; if(rcnt <=0) goto next  
;}
	lxi	h,dskbuf
iloop	mov	a,m
	cpi	1ah
	jz	finish
	inx	h
	; need to check the character here
	; put a character on the console.
	; register a has the byte.
	push	h
	putc
	pop	h
;
; keep track of the number of characters we write from 
; the buffer, 128 is the max.
;
	lda	rcnt
	dcr	a
	sta	rcnt
	cpi	0
	jnz	iloop
; goto outer loop
	jmp	loop
finish	equ	$
	close	rdfcb	
	post
	fmerr
	strcpy
	memset
	prestack
rdfcb	fcb
;name	db	'a.txt',0
dskbuf	equ	80h	
filenm	ds	16
rcnt	ds	1
	end
