#include "wto.mac"
#include "pre.mac"
#include "post.mac"
#include "prestack.mac"
#include "cpmcommon.mac"
#include "fcb.mac"
#include "fileopen.mac"
#include "fread.mac"
#include "fileclose.mac"
#include "fmerr.mac"
#include "packfd.mac"
#include "memset.mac"
#include "strcpy.mac"
#include "setdma.mac"
#include "printl.mac"
#include "display.mac"

	common
	org	100h
	pre
	wto	'Print file to console'
;
; prep a file name to open
;
;	lxi	h,rdfcb
	packfd	rdfcb,'A:TEST.TXT'
;
; open the file
;
	lxi	h,rdfcb
	open	hl	
;
; set up the dma buffer for file reads
;
	setdma	diskbuff
;
; make sure we set the sector count to 1
;
	mvi	c,2ch
	mvi	e,1
	call	bdos
;
; read records and print
;
loop	fread	rdfcb	
	jnz	done
;
; write the record to console
;
	display	diskbuff,'A'
	jmp	loop
;
; close file
;
done	lxi	h,rdfcb
	close	hl
;
; leave the program
;
	post
	fmerr
	memset
	strcpy
	prestack
rdfcb	fcb
diskbuff	ds	256
	end
