#include "wto.mac"
#include "pre.mac"
#include "post.mac"
#include "prestack.mac"
#include "cpmcommon.mac"
#include "fcb.mac"
#include "filedelete.mac"
#include "fmerr.mac"
#include "packfd.mac"
#include "memset.mac"
#include "startp.mac"
#include "strcpy.mac"
;#include "snap.mac"

	common
	org	100h
	pre
;
; collect start paramters from cp/m
;
	startp	front,list,count
;
; prep a file name to open
;
	packfd	rdfcb,'XXXXXXXX.XXX'
	memset	filenm,0,16
	strcpy	filenm,argb,16,0
	lhld	list	; get pointer to intended target file
	xchg		; into de
	lxi	h,rdfcb	; hl points to fcb
	call	packfn
;	snap	rdfcb,32
	delete	rdfcb
	post
	fmerr
	strcpy
	prestack
rdfcb	fcb
filenm	ds	16
	end
