#include "../../wto.mac"
#include "../../pre.mac"
#include "../../post.mac"
#include "../../prestack.mac"
#include "../../cpmcommon.mac"
#include "../../crlf.mac"
#include "../../radix.mac"
#include "../../mod.mac"
#include "../../comp.mac"
#include "../../divide.mac"
#include "../../multip.mac"
#include "../../binascii.mac"
#include "../../printl.mac"
#include "../../memset.mac"
#include "../../pushall.mac"
#include "../../popall.mac"
#include "../../seldrive.mac"



magic	equ	0e600h
seldskf	equ	magic +(3*9)
	common
	org	100h
	pre
	mvi	a,0
	sta	index
; for i = 0 ; i < 16; i++
floop	lda	index
;	mvi	c,11	; drive k
	mov	c,a
	inr	a
	sta	index
	seldriv
	shld	stat
        lxi     d,2     ; display in binary
        radix
        pushall
        memset	bigbuf,0,25
        popall
        binasci	s,bigbuf,,16
        printl	bigbuf
        crlf
	lhld	stat
	mov	a,h
	ora	l
	jz	next
	lda	index
	dcr	a
	mov	e,a
	mvi	d,0
	lxi	h,drivlst
	dad	d
	adi	'A'
	mov	m,a	
next	lda	index
	cpi	16
	jz	done
	jmp	floop
done	equ	$
	lxi	d,drivlst
	mvi	c,printf
	call	bdos
        post
        prestack
        mod
        comp
        mul
        div
bigbuf  ds      25
index	db	0
stat	dw	0
drivlst	db	'................',cr,lf,'$'	
        end

