;  work a bit like unix.  
;
;  find . -name string (print assumed)      Search the current drive 
;          ^^^^  full or partial name string.
;
;  find .  Prints all the file names on the current drive.
;
;  find * -name string     Search all the drives for the file name 
;  
#include "../../wto.mac"
#include "../../pre.mac"
#include "../../post.mac"
#include "../../prestack.mac"
#include "../../cpmcommon.mac"
#include "../../fcb.mac"
#include "../../fileopen.mac"
#include "../../fileseek.mac"
#include "../../fread.mac"
#include "../../fileclose.mac"
#include "../../fmerr.mac"
#include "../../packfd.mac"
#include "../../memset.mac"
#include "../../strcpy.mac"
#include "../../setdma.mac"
#include "../../printl.mac"
#include "../../puts.mac"
#include "../../putc.mac"
#include "../../display.mac"
#include "../../startp.mac"
#include "../../radix.mac"
#include "../../mod.mac"
#include "../../comp.mac"
#include "../../divide.mac"
#include "../../multip.mac"
#include "../../binascii.mac"
#include "../../snap.mac"
#include "../../crlf.mac"
#include "../../printerrno.mac"
#include "../../strlen.mac"
#include "../../strchar.mac"


	common
	org	100h
	pre
	startp	front,list,count
;
; handle start paramets
;
	lxi	h,fifcb
	packfd	'????????.???'
	lda	count
	ora	a
	jz	skip
; lets see if there is a complete file name in here.
	lhld	list+2
	xchg
	strchar	,12,'.'
; if de-> points to '.' then we assume this is a full
; file name.
	ldax	d	; get the byte
	cpi	'.' 
	jnz	skip1
; o.k. its a file name
	lhld	list+2
	xchg
	call	packfn
	jmp	skip
; clear out the name buffer (set to space)
skip1	memset	filenm,32,11
	lhld	list+2
; find the string length of the input file extension
	strlen
; a = number of bytes in string
;
	lhld	list+2
	xchg
	mov	b,a
	lxi	h,filenm
; copy the file extension string to filenm
	call	strcpy	
	lxi	d,filenm
	lxi	h,fifcb+9
	mvi	b,3
	mvi	c,0
	call	strcpy
skip	mvi	a,0	; preset drive to a:
	sta	curdriv
	lhld	list
	mov	a,m
	cpi	'.'	; if parameter is . then scan all drives
	jz	sknext
	sbi	'A'	; else only one drive
	sta	curdriv
sknext	equ	$
;	snap	filenm,3
;	snap	fifcb,22
;
; figure out how many drives are mounted
;
;
scanlp	equ	$
;
; select drive
;
	lxi	h,fifcb
	lda	curdriv
	mov	m,a
	mvi	c,0eh
	mov	e,a
	call	bdos
	call	dorest
	call	nxtdriv
;
; test for end of drive list
;
; if the drive search was a . search then all or a drive letter then we only
; search one drive, else all of them.
;
	lhld	list	; get pointer to first parameter
	mov	a,m
	cpi	'.'
	jz	scanlp
	jmp	done	
nxtdriv	lxi	h,curdriv
	inr	m
	ret
dorest	equ	$
	lxi	d,fifcb
	mvi	c,srchf
	call	bdos
	sta	errno
	inr	a
	rz
	call	prtname
;
; loop through the next entries
;
loop	lxi	d,fifcb
	mvi	c,srchn
	call	bdos
	sta	errno
	inr	a
	rz
	call	prtname
	jmp	loop
;
; print file name in fcb 
;
; errno has the value return from find first and next 
; directory entry.
; this is an index into the dskbuffer where the file name is
; located.  there can be up to 4 records in the buffer.
;
prtname	equ	$
;
; if console active, quit
;
	mvi	c,getcos
	call	bdos
	inr 	a
	jz	done
;
	lxi	h,dskbuf  
;
; errno has the index
;
	lda	errno
	ani	3
; multiply by 32 (size of entry in buffer)
	rlc
	rlc
	rlc
	rlc
	rlc
	mvi	d,0
	mov	e,a
; and bump up to the string
	dad	d
	inx	h
	lda	curdriv
	adi	'A'
	putc
	putc	':'
	mvi	b,8+3
prt1	push	b
	mov	a,m
	inx	h
	putc
	pop	b
	dcr	b
	jnz	prt1	
	crlf
	ret
done	equ	$
	post
	fmerr
	strcpy
;
; global storage
;
	prestack
filenm	ds	8+3	; space for constructing the file name
drivcnt	dw	0	; store the drive count here.
dskbuf	equ	80h
fifcb	fcb
curdriv	db	0
diskflg	db	0	; 0 = look on current drive only.
			; 1 = search all drives on the system.
fileflg	db	0	; 0 = find a file by name
			; 1 = find files by wild card
wild	ds	32	; storage for file name, or wild card key
	end
